### ISSUE TITLE
True/False Question with Multiple Performers

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#104]
[timebox: , complexity points: ]

As a user, I want a true/false question that asks if multiple performers were in a given movie, in order to make the game more challenging.

**User Expectations**
- A true/false question that includes a list of multiple performers

**Developer Requirements**
- `GenerateQuestion.js` modify the `getPerformerName` to return the entire `cast` object
- `MadLibs.js` modify questions that include `${movie.name}` to instead use the first cast array element for the name
  -  Construct new questions that name 2 `cast` members where `known_for_department` follow the guides below for true and false
  - For true questions: use Get Movie Credits endpoint, then filter the list for `cast` where `known_for_department` value **is equal to `Actor`**
  - For false questions: use Get Movie Credits endpoint, then filter at least one member of the `cast` where `known_for_department` value **is not `Actor`**

**Comment by xmercado** [comment]
cast object should be randomized because cast[0] and cast[1] always have known_for_department: "Acting".
