### ISSUE TITLE
Video Trailer Component

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#11]
[timebox: 180 min, complexity: 2]

As a user, I would like to see a trailer of the movie related to the question I answered when I answer correctly.

Assets
     -correct answer page
     -Video link(hopefully passed in from original API call)
     -possibly- https://lonelycpp.github.io/react-native-youtube-iframe/

Expected Outcome:
      -When user guesses correctly, a trailer for the movie will play on the correct answer screen.

**Comment by luceroweb** [comment]
@keshi2021 Please remove "Play/Pause" control since YouTube controls do the work well. Add function to calculate video width/height based on container width. Consider CSS `aspect-ratio` method mentioned by @SmiJa
