### ISSUE TITLE
Fix width of instructions on HowToPlay Scene

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#129]
Date Seen
4/1/22 3:25pm

Versions
Linux
Chrome
branch: origin/develop

Bug Description
The sections on the How To Play scene are different widths on a wide screen.

Steps to Reproduce

-Start a game on a wide screen in the web browser.
-Scroll to bottom of page and click on How To Play link on footer of Main Scene
-Scroll down page, observing as you go the width of each section('How To Play', 'Single Player Mode', 'Easy Single Player Mode'

Expected Behavior
Each of the sections on the How To Play Scene should have the same width, even on wide screens.

Troubleshooting/Testing Steps Attempted
changed line 134 in HowToPlay.js from maxWidth: "90%" to width: "90%".  This appears to be a viable solution.

Workaround
none

**Comment by luceroweb** [comment]
@srosenberg74 Resolved in class during demo/edit of `HowToPLay` scene
