### ISSUE TITLE
Write "How To Play" Instructions & Create View

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#14]
As a user I would like text instructions on how to play the "Guess the Movie" game so that I'll understand how the game works.

**User Expectations:**
- A page that tells the user how to play the game

**Developer Requirements:**
- Game play settings modal: #2
- Footer #52 
- Create `HowTo` scene
  - Add copy for each of the instructions listed below as `<View><Text>...</Text></View>` elements
- Link to `HowTo` from the 
  - ~~Main scene~~
  - Footer
  - ~~Settings Modal~~
- Instructions:
  - how to change game play mode (settings)
  - ex "click start" 
  - question game play
    - including the timer for default mode
    - including lives for easy play mode
  - correct answer scene
  - incorrect answer scene
  - Game over scene

**Comment by ProjectErostribe** [comment]
**Running List of Where Instructions Appear in Game**
Each location will need a unique set of instructions that guide the user through that feature

1. Main page animation
2. Settings modal

**Comment by ProjectErostribe** [comment]
I will do a demo on how to write technical instructions on 3/29/2022 for the team where we will live-code this task.
