### ISSUE TITLE
Game Over: iOS & Android (tall screens) MilkyWay image shows below drive-in foreground

### ISSUE THREAD

**Issue by garetshough14** [luceroweb/guess-the-movie#147]
**Date Seen**
4/6/22 10:30am

**Versions**
Android & iOS emulators
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
When on the "GameOver" scene on iOS or Android (if the screen aspect ratio is tall), you see the `MilkyWay` image showing at the bottom of the screen, below the drive-in foreground which should not be present.

**Steps to Reproduce**
1. Start the game in default Single Player mode
2. Let the timer run out
3. On the `GameOver` scene on iOS & Android (if the screen aspect ratio is tall) you can see the `MilkyWay` background image

**Actual Behavior**
When you are on the `GameOver` scene you will see the `MilkyWay` image showing at the bottom of the screen. 

**Expected Behavior**
The expected behavior of this specific scene is to have a black space below the drive-in movie foreground image. The `MilkyWay` image should not show below the foreground drive-in movie screen.

**Comment by SmiJa** [comment]
Here is a screenshot of the problem on iPhone 11 19.5/9 aspect ratio
![Image from iOS (1)](https://user-images.githubusercontent.com/1518017/163014509-a36d13b8-287e-4e00-aaa4-f179324891f7.png)
:

**Comment by srosenberg74** [comment]
Samsung Note 10+ 19/9 Aspect Ratio

![Screenshot_20220412-095916_Expo Go](https://user-images.githubusercontent.com/91571340/163016653-1c155aa0-7ad5-4287-b7bd-0ba3113c029b.jpg)
