### ISSUE TITLE
Game mode display bug

### ISSUE THREAD

**Issue by SmiJa** [luceroweb/guess-the-movie#148]
**Date Seen**
4/6/22 12:34pm

**Versions**
iOS 11
iOS X
iOS SE

**Bug Description**
When on the "GameOver" scene the box that displays the current game mode is pushed down on the scene. 

**Steps to Reproduce**

1. Open the game on an iOS device.
2. Play until you reach the GameOver scene.
3. The issue will be towards the top of the background image of the drive in image.

**Expected Behavior**
The game mode display box should be displayed along the border of the header.

**Comment by srosenberg74** [comment]
It's possible that line 43 in GamePlayMode.js may be the cause of this bug

**Comment by srosenberg74** [comment]
This code might be related to this issue:
```
top:
      Platform.OS === "ios" && height === "1334px"
        ? 40
        : Platform.OS === "ios"
        ? 48
        : 30,
```

**Comment by luceroweb** [comment]
@SmiJa is this issue exclusive to the `GameOver` scene or is it present in all scenes?

**Comment by luceroweb** [comment]
From @alberme 
try wrapping the `Nav.js` in this package instead of the inline solution in `GamePlayMode.js`
https://docs.expo.dev/versions/latest/sdk/safe-area-context/
