### ISSUE TITLE
Play Sound Unable to perform state update on unmounted component bug

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#156]
![playsoundbug](https://user-images.githubusercontent.com/91571340/162282478-e91f62d0-3d4f-4c00-9e04-6cdd2b440574.png)
![playsoundbug2](https://user-images.githubusercontent.com/91571340/162282491-447355aa-6863-4449-bd31-d3a0280d4860.png)
![playsoundbug3](https://user-images.githubusercontent.com/91571340/162282510-d2b55982-3c19-42ab-bf9d-4a12aa0fe3a4.png)

Date Seen
4/7/22 11:20am

Versions
Android
Android emulator
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

Bug Description
There is a warning reading "Warning: Can't perform a React state update on an unmounted component" that refers to playSound in the Timer.js file. This warning was observed on the Correct Answer scene and the Game Over scene in the emulator. 

Steps to Reproduce
It is difficult to reproduce the bug. The root cause needs to be identified in order to consistently reproduce the issue.

1. Start game
2. Play game and answer question either correctly or incorrectly.
3. During game play this warning appeared.  It appeared on the both the CorrectAnswer Scene and GameOver Scene.  It is a difficult error to reproduce and may take many play-throughs to re-appear. I was playing in Single Player Mode when I reproduced it.  I'm not sure if it is exclusive to Single Player Mode or if it also exists in Easy Single Player Mode.

Actual Behavior
Console warning shows up saying "Can't perform a React state update on an unmounted component" during gameplay(has been observed on both CorrectAnswer Scene and GameOver Scene).  So far I have only observed it in the emulator. Not sure if it occurs on web.

Expected Behavior
There will be no warnings in the console.

Troubleshooting/Testing Steps Attempted
N/A

Workaround
none

**Comment by alberme** [comment]
I was not able to reproduce that exact warning, however I did run into a different warning related to initializing audio
Sound also no longer plays after this warning occurs
![image](https://user-images.githubusercontent.com/3313769/162838612-b0a62954-f4e1-49b8-bc28-047f7f50b504.png)

**Comment by alberme** [comment]
Now was able to reproduce but with an additional warning. My suspicion is leading towards the cleanup function in useEffect
![image](https://user-images.githubusercontent.com/3313769/162839572-432b67ec-9a89-4f17-91e3-b7ffeccc4c03.png)

**Comment by alberme** [comment]
This might not be related to this issue however it is worth noting in case we run into these errors in the future. 

On Android, this error is from Trailer.js in useEffect which does not deal with sounds.
![image](https://user-images.githubusercontent.com/3313769/162843210-e076a2c9-8b91-4e11-8137-5ef00a913069.png)

On Web, this error is from CorrectAnswer however it may be related to Trailer.js
![image](https://user-images.githubusercontent.com/3313769/163075870-84234a86-c621-4e2e-904b-6b15e4c8d657.png)

The service worker navigation error can be fixed using the youtube-nocookie url
https://stackoverflow.com/a/68000279
