### ISSUE TITLE
Developer Credits Scene

### ISSUE THREAD

**Issue by ProjectErostribe** [luceroweb/guess-the-movie#18]
[timebox: , complexity points: ]

As a user I would like to see a page that tells me more about who made the game that I am playing.  

**User Expectations:**
- View list of developer names

**Developer Dependencies:**
- Scene component must be named "DeveloperCredits" and listed in the scenes list as "DeveloperCredits"
- Design Developer Credits Scene to agree with Lunacy mock-up
- Gather a list of all developer names as the developer would like them to appear in the credits
- List names alphabetically by last name: https://docs.google.com/spreadsheets/d/1zN14wqkQ8nVfM5kNW42Qrp9eh6DBufmEqb1tVDg94gc/edit#gid=0

**Comment by luceroweb** [comment]
@ProjectErostribe this is definitely a missing feature. Let's add this to the site footer.

**Comment by garanico** [comment]
@Tesfa-Worku @garetshough14 Link to developer names has been added to the user story
