### ISSUE TITLE
About Bitwise Workforce Training Scene

### ISSUE THREAD

**Issue by ProjectErostribe** [luceroweb/guess-the-movie#20]
As a user I would like to know more about Bitwise and the Workforce Training Program in order to understand why this game has been made.

User Expectation:
- Link to lean more about BitWise Workforce Training
- Link to Developer Credits scene

Developer Dependencies:
- Design About Bit-wise Workforce Training to agree with Lunacy mock-up
- Page copy (see below)
- "Learn More" link https://bitwiseindustries.com/services/workforce-training/classes/
- "Developer Credits" scene state name is "DeveloperCredits"

**About the "Guess The Movie" Game:**
This game was created in order for our developer team [link to "Developer Credits" scene] to lean more about React-Native, Redux, Axios, and dynamic question generation using a live data base.

**About Workforce Training:**
Our curriculum doesn’t come from textbooks, it comes directly from practicing industry experts. Our system of teaching is hands-on and up-to-date with current practices. Learn more [link to https://bitwiseindustries.com/services/workforce-training/classes/]

**Comment by luceroweb** [comment]
@ProjectErostribe I love this idea. Let's add this link to the site footer.
