### ISSUE TITLE
Main Scene Layout incorrect in Landscape mode

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#201]
Date Seen
4/26/22 12:42pm

Versions
Web Browser
Chrome
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

Bug Description
The Main Scene layout is incorrect in Landscape mode.  Only the top half of the screen is visible and the 'Start Game' button and the footer are completely hidden unless the user scrolls down.

Steps to Reproduce

1. Start Game with device in Landscape Orientation
2. Observe that only the top section of the Main Scene is in the view, cutting off most of the animation, the start button, and the footer

Actual Behavior
The layout of the Main Scene cuts off all but the top of the Scene when in Landscape orientation.

Expected Behavior
The entire Scene, or at least all of the important UI elements, will be visible in all screen orientations on all devices.

Troubleshooting/Testing Steps Attempted
N/A

Workaround
none

**Comment by luceroweb** [comment]
@srosenberg74 please add a screenshot of the issue
