### ISSUE TITLE
Main scene:text alignment

### ISSUE THREAD

**Issue by firezgi** [luceroweb/guess-the-movie#202]
Date Seen
4/26/22 12:30pm

Versions
Android emulator
iOS
Chrome
develop

Bug Description
Text in the movie theater is not aligned with text line 

Steps to Reproduce
Open the game and on the first scene you will see the problem on the background image

Expected Behavior
The text should align with the line 

Actual Behavior
The text is not aligned with the line

Troubleshooting/Testing Steps Attempted
N/A

Workaround
none

**Comment by luceroweb** [comment]
@keshi2021 please add a screenshot of the issue

**Comment by SmiJa** [comment]
The updated image for the marquee
![marqueeBackground](https://user-images.githubusercontent.com/1518017/165397528-c8a4b6b6-99d0-4a03-8634-e6068191cd4d.png)

**Comment by SmiJa** [comment]
The new image was not centered properly due to it not being the trimmed version of the marquee image. Also The text ("React MVP's" and "Product)") on the left side of the marquee as been requested by @luceroweb to be pulled in closer to the middle text.
