### ISSUE TITLE
Correct Answer Scene Layout Incorrect in Landscape mode

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#203]
Date Seen
4/26/22 12:55pm

Versions
Web
Chrome
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

Bug Description
The 'Next Question' button is cut off while in landscape orientation.

Steps to Reproduce

1. Start a game with device in landscape orientation
2. Answer a question correctly
3. Observe that the 'Next Question' button is not inside the view and the user must scroll down to see it and interact with it

Actual Behavior
The 'Next Question' button is not visible in landscape mode on the 'Correct Answer' Scene.

Expected Behavior
All UI elements will be in the view regardless of which orientation the user's device is in.

Note: Developer may consider removing the marginTop from the 'Next Question' button as a possible fix for this bug

Troubleshooting/Testing Steps Attempted
N/A

Workaround
none

**Comment by luceroweb** [comment]
@srosenberg74 please add ~~a bug description in the standard format and~~ a screenshot of the issue.
