### ISSUE TITLE
Round clock

### ISSUE THREAD

**Issue by Hiwot-Beshe** [luceroweb/guess-the-movie#35]
**Feature: Game play:  Timer**

[timebox: 60 min, complexity: 2]

As a user, I want to see a count down clock animation that shows me know how much time I have left to answer the question.

**User Expectations**
   - Display time clock animation Question screen

**Developer Requirements**
- Choose colors from list provided in Epic document
- Display count down clock Question page screen.
- See sample npm package and reference image in this ticket

**Comment by luceroweb** [comment]
![image](https://user-images.githubusercontent.com/10747669/156455010-515b8ce9-d024-4897-afc0-b7bec5a7ca1c.png)
Us this reference image to give you a general idea of how to design the countdown clock

**Comment by luceroweb** [comment]
Possibly use this package or one like it:
https://www.npmjs.com/package/react-native-countdown-circle-timer
