### ISSUE TITLE
Add in Genre related True/False Questions

### ISSUE THREAD

**Issue by garanico** [luceroweb/guess-the-movie#40]
[timebox: 2 hours, complexity points: 2]

As a user, I would like to see more true/false questions about the movie genre so that game play will be more interesting.

As a developer, I would like to integrate different information from the API to generate a wider variety of questions for the player to answer.

**Expected outcome:**
-Add genre related true statements and hard-coded false statements to the Mad Libs Array. 

**Developer Dependencies**
- Get Details API data object
  - The 'genre' value is provided as a string by the Details API https://developers.themoviedb.org/3/movies/get-movie-details
- Mad Libs Array

Examples:

**True Statements: (data driven)**
${title} is considered a ${genres.name}`
${title} is categorized under the ${genres.name} genre.

**False Statements: (hard codded)**
Kill Bill is a romantic comedy.
Captain America is categorized under the "musicals" genre.

**Comment by xmercado** [comment]
@SmiJa @Tesfa-Worku @keshi2021 Please do not forget to tag the ticket id in your commit message.

**Comment by xmercado** [comment]
Used popular movies and genre list API endpoints instead of movie details because existing code already uses popular movies endpoint and contains only genre_ids with no names.

**Comment by xmercado** [comment]
Used genreName, which comes from genre_ids from popular movies, instead of genres.name from movie details.
