### ISSUE TITLE
Header Styles

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#45]
[timebox: , complexity points: ]

As a user, I want a page header to tell me the name of the game on each page so that I know I am still in the game UI.

**User Expectations**
- a header on every page containing the text "The Movie Game"

**Developer Requirements**
- Include only the project name "The Movie Game" in the header, centered, using the Limelight font
- Follow the design in the Lunacy mock-up
  - font color & bottom border color: #F2D379
  - no background color

**Comment by darlanebrown** [comment]
**Page, needs to  be adjusted**  

- so you don't have to scroll crazy, or 
- 86 it, 
- and make another page within the margin
