### ISSUE TITLE
Fix Timer Position Bug(on mobile)

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#53]
**Date Seen**
3/4/22 10:30am

**Versions**
Android and iPhone
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
On mobile(Android and iPhone) the timer overlaps the question.

**Steps to Reproduce**
1. Start the game on a mobile device
2. View Question page
3. Timer overlaps the question texr.

**Actual Behavior**
On mobile devices, the timer overlaps the question text on the Question Scene

**Expected Behavior**
The timer should be in a position on all devices in which it will not overlap or obstruct the question text.

**Troubleshooting/Testing Steps Attempted**
None so far

**Workaround**
None so far

**Comment by luceroweb** [comment]
![Screenshot_timer_overlaps](https://user-images.githubusercontent.com/10747669/156849880-2c72dda0-19d8-46b8-a625-c076e4387a32.png)

**Comment by luceroweb** [comment]
Issue still exists in iOS and will be resolved in another bug ticket.
