### ISSUE TITLE
"gamePlayMode" Redux state

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#54]
[timebox: , complexity points: ]

As a user, I'd like my game play mode to be stored so that it is visible below the header throughout the app.

**User Expectations:**
- Game play mode is saved
- Game play mode is displayed below the header

**Developer Requirements:**
- Add `gamePlayMode` to Redux `initialState` with an initial string value of `singlePlayer`
- Add a `SET_GAME_PLAY_MODE` reducer that accepts a string action called `gamePlayMode`

**Comment by srosenberg74** [comment]
@garanico @eyobel7k This looks great!  The only issue is with the name of the gamePlayMode state.  The initialState needs to be singlePlayer, but I think the text displayed should be "Single Player Mode" or "Single Player" like you have it, so I think in the GamePlayMode.js maybe there needs to be something that decides what text is actually displayed based on the state.
