### ISSUE TITLE
Fix Movie Trailer Placement

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#56]
**Date Seen**
3/9/22 5:40pm

**Versions**
Linux
Chrome, Android
[develop branch](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
On the Game Over scene, the Trailer is either larger or smaller than the drive in movie background image, depending on the break-point.

**Steps to Reproduce**
1. Start the game
2. Choose the incorrect answer
3. The "GameOver" scene is displayed
4. The YouTube trailer is either larger or smaller than the drive in movie background image, depending on the break-point

**Actual Behavior**
The YouTube trailer container is not the same size as the drive in movie background image area

**Expected Behavior**
The YouTube trailer should exactly match the size and position of the drive in movie screen in the background image

**Troubleshooting/Testing Steps Attempted**
Attempted resizing the screen to multiple break-points once on the GameOver scene.

**Workaround**
No known work-arounds

**Comment by ProjectErostribe** [comment]
I need someone at workforce training to contact me ASAP.

I have been emailing and reaching out since I left. I need proof this apprenticeship so I can go back to school to get my degree.

I am running out of time to fill out documents and take the assessments I need. 

Someone needs to email me at x@PaidamoyoJanetAzehko.com

**Comment by luceroweb** [comment]
@ProjectErostribe I forwarded your email request to HR so they can confirm your employment. 
Please note that GitHub tickets are not an appropriate place to post requests outside of the scope of the project.
