### ISSUE TITLE
Easy Mode: Disable timer

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#74]
[timebox: , complexity points: ]

As a user, I want the timer to be disabled when I've selected the "easy" single player mode so that I have more time to choose my answer.

**User Expectations:**
- The timer will not run when `gamePlayMode` is set to `easySinglePlayer`

**Developer Requirements:**
- When the value of the Redux state `gamePlayMode` is set to `easySinglePlayer`, then do not load the `<Timer ...>` component on the `Question.js` page.

**Comment by firezgi** [comment]
I put a default for gamePlayMode "easySinglePlayer"
