### ISSUE TITLE
Easy Mode: Add `lives` and reducers to Redux

### ISSUE THREAD

**Issue by luceroweb** [luceroweb/guess-the-movie#80]
[timebox: 15 min, complexity points: 1]

As a developer, I need decrease or reset the number of lives for a given user during the game in order so that I can count and store the number of lives remaining. 

**User Expectations:**
- none, not user facing

**Developer Requirements:**
- Add `lives` with a default value of `3` to the Redux `initialState` object
- Add a `DECREASE_LIVES` case to the reducer
  - When called, subtract 1 from the `lives` Redux state
- Add a `RESET_LIVES` case to the reducer
  - When called, reset the `lives` Redux state to `3`

**Comment by xmercado** [comment]
Changed SUBTRACT_A_LIFE to DECREASE_LIVES to keep consistency among reducers like INCREASE_WINNING_STREAK.

**Comment by luceroweb** [comment]
> Changed SUBTRACT_A_LIFE to DECREASE_LIVES to keep consistency among reducers like INCREASE_WINNING_STREAK.

@xmercado good call. ~~I'll make the same update in the ticket description.~~ I see you did that already. Thanks!
