### ISSUE TITLE
Fix Game Play Mode indicator position on ios

### ISSUE THREAD

**Issue by srosenberg74** [luceroweb/guess-the-movie#87]
**Date Seen**
3/17/22 11:10am

**Versions**
iOS in Expo app (on real device)
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
The position of the Game Play Mode indicator is too low on ios.

**Steps to Reproduce**
1. Load the game
2. The Game Play Mode indicator is too far below the header, with blank space between it and the header 

**Actual Behavior**
The Game Play Mode indicator appears too low on ios.  It should be on the bottom border of the header so that it doesn't obstruct other content on the Scenes.

**Expected Behavior**
The Game Play Mode indicator should be positioned on the bottom border of the Header on all devices and screen sizes so that it doesn't obstruct other content on the Scenes.

**Troubleshooting/Testing Steps Attempted**
- Scroll page down and up, content is covered
- Switched between pages, position is consistent
- Content position behaves like "fixed" or "sticky" position in the browser

**Workaround**
None so far

**Comment by luceroweb** [comment]
@garanico @SmiJa both report that Game Play Mode test is positioned correctly on their devices.
@alberme please add a screenshot of your device to confirm that the issue still exists.

**Comment by garanico** [comment]
Attached are screenshots from my phone with correct gamePlayMode indicator placement.

![question-scene](https://user-images.githubusercontent.com/82012415/159345269-eec8c08f-8df4-4b7d-8113-a5332374ff95.PNG)
![gameplaymode-indictor-startscreen](https://user-images.githubusercontent.com/82012415/159345273-7922241b-db8c-48a5-b133-85c88f36e613.PNG)
![gameover-scene](https://user-images.githubusercontent.com/82012415/159345274-09d52f74-794f-4a0f-8c8e-27e8286eb849.PNG)

**Comment by alberme** [comment]
Screenshot from 1st Gen iPhone SE (2016). A flex style might be pushing the play mode indicator down as screen size gets smaller.
![Image from iOS](https://user-images.githubusercontent.com/3313769/159347041-f7b2b8f1-94eb-4e0d-891f-99dce989c47a.jpg)

**Comment by xmercado** [comment]
I get the same bug as Albert on iPhone SE 2020.

**Comment by luceroweb** [comment]
@alberme @xmercado that suggests to me that this issue may be screen size related, and not directly related to to iOS. @xmercado please try testing this ticket on different screen sizes in the browser to see if you can reproduce the issue.

**Comment by luceroweb** [comment]
@xmercado thanks for testing on different screen sizes in the browser. We confirmed that the issue is specific to iOS and as @SmiJa suggested is likely related to a position top value ternary for iOS.
