### ISSUE TITLE
Fix Wrong Answer Scene text container sizing 

### ISSUE THREAD

**Issue by eyobel7k** [luceroweb/guess-the-movie#98]
[timebox: 2hr, complexity:2]
As a user I want to see the wrong answer scene text to stay inside the movie screen image at all times, so that the white drive-in movie screen doesn't show.

**User Expectations:**

- The elements inside of the  `.answerContainer` View covers the white screen image in the background for all screen sizes.

**Developer Requirements:**
- #91 is required to complete this ticket
-  WrongAnswer.js
  - Place purple `.answerContainer` section over the drive-in movie screen in the background image at all breakpoints.
- test  on all platforms : web, ios and android

**Comment by luceroweb** [comment]
![Screenshot from 2022-03-23 11-09-42](https://user-images.githubusercontent.com/10747669/159767400-934c44cb-3fa0-4a88-816e-99ec1c281bd3.png)
![Screenshot from 2022-03-23 11-09-50](https://user-images.githubusercontent.com/10747669/159767404-62460715-9b3f-4d6c-9c8d-3791b9a50491.png)
![Screenshot from 2022-03-23 11-09-59](https://user-images.githubusercontent.com/10747669/159767408-a3e32875-629c-4946-8fb0-375bc65c7c2d.png)
